### ISSUE TITLE
Idea - Island Maker Boat Type

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [jglrxavpok/Moar-Boats#10]
Basically this would allow the player to get out of the boat and start placing blocks in middle of ocean. While Shift clicking boat (One piece inspired idea)

**Comment by jglrxavpok** [comment]
There is no way to sit in the boat for the moment but I plan to add one.
Though, I think it could be made automatic, with a new module: You input blocks and set a block frequency, and the boat places the blocks you've given it?

**Comment by P3rf3ctXZer0** [comment]
Like it ;)

**Comment by jglrxavpok** [comment]
The Dispenser module implemented in 1.3.0 (not yet released as of the writing of this comment) can place a 3 blocks high column behind the boat ;)
