### ISSUE TITLE
1.16.5 Mapping Table Text?

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#100]
Testing Moar-Boats in 1.16.5, using following mods loaded:

curios-forge-1.16.5-4.0.5.2.jar
DungeonCrawl-1.16.5-2.3.2.jar
jei-1.16.5-7.7.1.118.jar
journeymap-1.16.5-5.7.3.jar
kotlinforforge-1.14.0-obf.jar
moarboats-1.16.3-8.0.0.0-beta3.jar
sounddeviceoptions-1.4.2.jar

I placed the mapping table and noticed "moarboats.inventory.mapping_table" text as shown below

![image](https://user-images.githubusercontent.com/1753699/128610807-243b2c0d-22e0-441e-92fd-8beee3f598ea.png)

**Comment by jglrxavpok** [comment]
Fixed in 1.19 port
