### ISSUE TITLE
1.16.5 Journeymap waypoints

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#101]
Testing Moar-Boats in 1.16.5, using following mods loaded:

curios-forge-1.16.5-4.0.5.2.jar
DungeonCrawl-1.16.5-2.3.2.jar
jei-1.16.5-7.7.1.118.jar
journeymap-1.16.5-5.7.3.jar
kotlinforforge-1.14.0-obf.jar
moarboats-1.16.3-8.0.0.0-beta3.jar
sounddeviceoptions-1.4.2.jar

The "Waypoints from other mods" is not populating. Likely a change in Journeymap?

**Comment by jglrxavpok** [comment]
Journeymap was not updated to 1.16+ when I released Moar Boats 1.16.5, that's why.

I'll add support back in the next release (when it comes)

**Comment by jglrxavpok** [comment]
Returning in 1.19
