### ISSUE TITLE
Idea - Cabin boat / Emergency spawn point

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [jglrxavpok/Moar-Boats#11]
Drop anchor and set a spawn point - even if danger is nearby.

**Comment by jglrxavpok** [comment]
I really like this idea, I'll see what I can do about it!

**Comment by jglrxavpok** [comment]
The feature is ready for 1.2.0!
Last commit https://github.com/jglrxavpok/Moar-Boats/commit/1f4fe7bfb6410b7c7e8d9bbc0427198d82e7a308

Screenshots: 
![https://raw.githubusercontent.com/jglrxavpok/Moar-Boats/1.2.0/screenshots/anchor_gui_moving.png](Screenshot of anchor gui)
![https://raw.githubusercontent.com/jglrxavpok/Moar-Boats/1.2.0/screenshots/anchor_outside.png](Screenshot of anchor module)

**Comment by P3rf3ctXZer0** [comment]
Nice; thank you! @jglrxavpok
