### ISSUE TITLE
Waterborne redstone should slow down boats to a stop, not just turning the engine off

### ISSUE THREAD

**Issue by WesTroy** [jglrxavpok/Moar-Boats#25]
Great mod - super fun! Thanks -

Forge-1.12.2-14.23.2.2654
moarboats-1.12.2-1.3.1

Am I missing something here (see gif)? I can't stop/lock the boat with the waterborne redstone. If I watch the GUI while it passes over the redstone, it does briefly say "Locked by redstone"... but the boat continues on.

https://giphy.com/gifs/u4aVAF9ZemMcgNrLKl

Guidance is much appreciated - thanks again!

**Comment by jglrxavpok** [comment]
The waterborne redstone only stops the engine but does not slow down the boat in this release, I will make it so in the next

**Comment by WesTroy** [comment]
Sounds good - thanks for your reply. Keep up the great work.

**Comment by WesTroy** [comment]
Confirmed to work (https://imgur.com/0yIoM0C). Awesome.
