### ISSUE TITLE
Crash when add icebreaker

### ISSUE THREAD

**Issue by Tototi1** [jglrxavpok/Moar-Boats#31]
when i add an icebreaker to a boat with furnace and rudder, i crash
the boat was stuck to the ice when I wanted to add iceBreaker
Crash report : 
https://pastebin.com/wTyGGSq5

**Comment by jglrxavpok** [comment]
Fixed in commit https://github.com/jglrxavpok/Moar-Boats/commit/1ae47de14e9c85a37e076aec7037c287e8cbca8a

The next release with this fix should appear on CurseForge in a hour or so there: https://minecraft.curseforge.com/projects/moar-boats/files/2577371
