### ISSUE TITLE
[Suggestion] Mapping table

### ISSUE THREAD

**Issue by jglrxavpok** [jglrxavpok/Moar-Boats#36]
From Cheese_Almighty on Reddit: (https://www.reddit.com/r/feedthebeast/comments/9aq18d/the_new_update_for_moar_boats_adds_tanks_and/e4xhpen/ )

All that is seemingly missing is a golden "itinerary" that can be changed remotely.

This maybe be easier to accomplish if these routes were created on a mapping table, instead of on the boat itself. Resulting in a separate item with an UUID. This will also probably make it easier to add some sort of landmark system in the long run. Just enter (x,z) coords, instead of the clicking on the map.

**Comment by jglrxavpok** [comment]
From wormzjl on Reddit:

If you use a dock, the boat itself can be a pure visual effect instead of a in-world entity while docked. This would make things looked better and is more friendly for performace.

This will also make automation easier, since one can refer to the dock directly instead of inputting the coordinate when making paths (looking at the suggestion about mapping table above).

**Comment by wormzjl** [comment]
![image](https://user-images.githubusercontent.com/2989009/44724144-7838b000-ab04-11e8-8be1-b2cba0c57d5f.png)
Just a reference for the port
