### ISSUE TITLE
Right click behavior (Suggestion)

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#47]
When Rt Clicking on a configured boat, the first tab to display should be engine controls. Especially when some tabs only display "Nothing to configure"

Also Instead of the X to the right removing the item which is not intuitive, can you make it a button in the body of the tab in place of the "Nothing to configure" text?

OR

Make a single tab for the optional add on items that do not have controls. (Seat, Ice Breaker, Rudder, etc). Allow us to easily add remove the options in this tab which can also show what slots are available.

**Comment by jglrxavpok** [comment]
Done in 4.0.0.0
