### ISSUE TITLE
Ver 4.0.0.0b item duplication bug

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#49]
In the Mapping Table interface, if you Shift Click an item in your inventory the item duplicates. If you shift click on a stack size of less than a full stack they all duplicate,

**Comment by jglrxavpok** [comment]
Actually affects all interfaces
https://github.com/jglrxavpok/Moar-Boats/commit/c456bbe73f8102b9fb4a9a4b4c364e8d99d59d85 should fix it.
