### ISSUE TITLE
4.0.0.0b5 Waypoints list

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#55]
![image](https://user-images.githubusercontent.com/1753699/47999294-2302b700-e0d0-11e8-86c0-6f71e2553b59.png)

![image](https://user-images.githubusercontent.com/1753699/47999234-edf66480-e0cf-11e8-8134-b1109e5b7281.png)

Not able to pull in the waypoints from Journeymap. Refresh List Button does not seem to work.
Waypoint path is - ..\minecraft\journeymap\data\mp\Minecraft~Server\waypoints

Remove button does not refresh the list, to show removal. Leaving the gui and coming back to it does show the removal works.

**Comment by jglrxavpok** [comment]
What name did you give to the server in the multi-player menu? Apparently
that's what JourneyMap uses, I will try to fix it asap

**Comment by jglrxavpok** [comment]
Fixed in eab580f0f230a413bf0b5ea166de52b64664bd66 (will be available in 4.0.1.0)
