### ISSUE TITLE
Faux item render in F5

### ISSUE THREAD

**Issue by EvertX** [jglrxavpok/Moar-Boats#63]
Version 4.1.0.0

Tested with just your mod (and forgelin obv.)

In F5 there is a strange item being rendered. it looks like an obsidian hammer with a question mark as a handle. See screenshot.
![wist](https://user-images.githubusercontent.com/7046024/51109330-38ddd800-17f5-11e9-9da6-66b8410a7a9c.png)

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/4

**Comment by jglrxavpok** [comment]
Fixed in commit https://github.com/jglrxavpok/Moar-Boats/commit/98432acc523765733133eb5baae4629e5e0800f7

The 4.1.0.1 version has the fix: https://minecraft.curseforge.com/projects/moar-boats/files/2660629
