### ISSUE TITLE
Crash when placing charging blocks

### ISSUE THREAD

**Issue by firedoom13** [jglrxavpok/Moar-Boats#66]
when placing ether discharger or charger block it crashes. may cause from Gregtech CE. But I don't know.
https://pastebin.com/FVqDiPiG

**Comment by jglrxavpok** [comment]
This should be fixed in version 4.1.0.2: https://minecraft.curseforge.com/projects/moar-boats/files/2663207 (you may have to wait for CurseForge validation)

Fixed in commit 71f0dfd8310a9a9b3f9a124aa577989f6608a68b
