### ISSUE TITLE
Crash when adding fishing module with chest module or vice versa

### ISSUE THREAD

**Issue by Nakuta** [jglrxavpok/Moar-Boats#67]
[crash-2019-01-18_18.21.21-server.txt](https://github.com/jglrxavpok/Moar-Boats/files/2774839/crash-2019-01-18_18.21.21-server.txt)

Whenever I either add a fishing rod and then a chest, or a chest and then a fishing rod to a boat, the game will crash and continue to crash every time I attempt to load that world.

Please see the attached crashlog.

**Comment by firedoom13** [comment]
I have the same problem. The error ,org/jglrxavpok/moarboats/common/NewConfig, happen in my crash report as well. um check if moar boats config file is generated in the config folder. because it won't generate in mines. It should be called moarboats.cfg.

**Comment by jglrxavpok** [comment]
I have received multiple reports about the New Config error. Sadly I can't
investigate right now, I'll try to get it fixed asap (probably on Monday
21st?...)

**Comment by jglrxavpok** [comment]
This should be fixed in version 4.1.0.2: https://minecraft.curseforge.com/projects/moar-boats/files/2663207 (you may have to wait for CurseForge validation)

Fixed in commit 71f0dfd8310a9a9b3f9a124aa577989f6608a68b

**Comment by jglrxavpok** [comment]
In theory, your save should not be corrupted and should be usable.
