### ISSUE TITLE
Suggestion: Helm auto-locking

### ISSUE THREAD

**Issue by DPattee** [jglrxavpok/Moar-Boats#71]
I had a one-way map installed on one of my furnace-powered boats. The path I'd set in wasn't working properly (the end point was a bit far from where I wanted it).

As I was deleting points on the installed map, I deleted the last assigned point and all of a sudden the boat took off!

It had been 'stopped' since it had reached its last marker, I didn't even think about locking the engine. So as soon as that last position was deleted, it just went in to full speed 'straight ahead' mode :(

**Comment by jglrxavpok** [comment]
Would an auto-lock when editing the map work?

**Comment by DPattee** [comment]
Yea, I can't imagine a scenario where I'd ever want the boat to be moving while I had the map screen open.

**Comment by jglrxavpok** [comment]
Done in v4.1.2.0
