### ISSUE TITLE
Mapping Table Durability 

### ISSUE THREAD

**Issue by instinxx** [jglrxavpok/Moar-Boats#76]
Mapping Table Durability needs to be at least as high as a crafting table. Currently one hit from a hand breaks it causing it to lose the golden ticket with 50+ waypoints....

**Comment by jglrxavpok** [comment]
Fixed in commit 2777c6a3e3c414ce2e434fef3b4e33d06fe4822e
Will be inside the upcoming 4.1.1.1 update
This also fixes mapping tables not dropping their contents when destroyed
