### ISSUE TITLE
Ice Breaker doesn't like angles

### ISSUE THREAD

**Issue by duncanwebb** [jglrxavpok/Moar-Boats#79]
Version: moarboats-1.12.2-4.1.1.0

When observing the ice breaker it doesn't work when travelling at an angle, see image
![ice breaker](https://user-images.githubusercontent.com/4198031/57980254-140aa300-7a29-11e9-81f7-dcfc94fa80ff.png)

This image shows that the ice breaker is breaking three blocks in front of the boat and another three in front of these.
![ice breaker 2](https://user-images.githubusercontent.com/4198031/57980306-1d483f80-7a2a-11e9-8257-f48af9687c96.png)

I reckon the cause is the breaker is clearing an area too far forward, it if cleared the five blocks in front of the boat is would work.

Thanks for the mod

**Comment by jglrxavpok** [comment]
Fixed in 83bba16174e7a4f6acfd8fe4a7d442b495f7f4c1 (v4.1.2.0)
