### ISSUE TITLE
Allow a full cargo boat to leave

### ISSUE THREAD

**Issue by duncanwebb** [jglrxavpok/Moar-Boats#81]
When a boat is being loaded using a hopper and a waterborne redstone conductor is holding it there and the boat cannot be filled any more then it will need to leave the loading station.

While I don't think this is going to happen very often it would be nice to allow the boat to automatically bypass the waterborne redstone conductor when there is a hopper above the boat.

Here is an example, two unloading and loading stations with a full boat that is stuck as the hopper still has items.

Both the stations are the same in terms of hoppers and redstone and you can see here the build
![loading-station](https://user-images.githubusercontent.com/4198031/60197519-d37c2180-983f-11e9-90da-569c21ba400e.png)

Here is a full boat, the hopper still has something in it
![full boat](https://user-images.githubusercontent.com/4198031/60197469-b9424380-983f-11e9-8a4b-83b01ac575c5.png)

So the boat won't move.
![boat still loading](https://user-images.githubusercontent.com/4198031/60197481-bd6e6100-983f-11e9-8485-d284b11293e8.png)

**Comment by jglrxavpok** [comment]
You accidentally made me discover a enormous oversight in the way waterborne redstone components work.
In short, they did not pay attention to their orientation when retransmitting power

v4.1.2.0
![2019-06-26_22 56 29](https://user-images.githubusercontent.com/5427890/60214553-046f4d00-9866-11e9-9182-5500e75ee2c4.png)

v4.1.2.1 (soon to be released)
![2019-06-26_22 56 48](https://user-images.githubusercontent.com/5427890/60214508-f0c3e680-9865-11e9-8acc-2b9c9da79fcb.png)


Going back to the topic of the issue, the problem can be solved using redstone and a redstone waterborne comparator, here's my setup:

Top View: (highlighted comparator is in subtraction mode)
![image](https://user-images.githubusercontent.com/5427890/60214777-7778c380-9866-11e9-9e21-4836915258c3.png)

Side-View 1: (highlighted comparator is a **waterborne** redstone comparator)
![image](https://user-images.githubusercontent.com/5427890/60214836-98411900-9866-11e9-99dc-4562d719e084.png)

Side-View 2:
![image](https://user-images.githubusercontent.com/5427890/60214846-a000bd80-9866-11e9-9f8f-ec7b30ed739c.png)

The idea is to let free of the boat is:
+ The boat is full
+ The hopper is empty

I hope this can help you!

**Comment by jglrxavpok** [comment]
I forgot to mention the setup does not work in v4.1.2.0 due to the issue with transmitting power via waterborne redstone components.

**Comment by jglrxavpok** [comment]
The fix is going to break your current designs as you use the "feature" that comparators stop boats when they are not empty, which is not how the component was supposed to work :/

**Comment by duncanwebb** [comment]
It wasn't my first design either, don't know how I discovered waterborne comparators emitted redstone in all directions, it makes unloading very simple to manage. My first design is described in https://youtu.be/lfEKYLCzhkQ.

I don't fully understand what you are doing in the pictures. It looks like you are holding the boat and using a comparator to check the chest fullness, at the back of the boat and loading from the front. Is this correct?

One problem with this is mix of items in the cargo, you won't get a signal of 15 unless the boat has complete stacks.

Ideally, as this is boat version of Steve carts so we really need a cargo manager, to deal with the logic. Hoppers are way to slow to fill a chest.

Looks like a block of bedrock is a creative engine. :-)

**Comment by jglrxavpok** [comment]
I've added a Cargo Stopper: this new waterborne block will behave exactly like the v4.1.2.0 waterborne comparator, ie send a signal in all directions if a boat with some cargo is in front.

Empty
![2019-06-28_23 50 32](https://user-images.githubusercontent.com/5427890/60373180-95c5f700-99ff-11e9-84a8-4b88449fb0ac.png)

With some items
![2019-06-28_23 50 36](https://user-images.githubusercontent.com/5427890/60373194-a1b1b900-99ff-11e9-882c-3e657da42ec7.png)

I'm also currenly implementing your special case for hoppers as this is probably the easiest way to take full boats into account right now.

As for the Cargo Manager, this will probably have to wait for the 1.13 port.

**Comment by duncanwebb** [comment]
Thank you very much, this seems like a really good compromise, easy to implement in the game. Thank you for listening.
