### ISSUE TITLE
Boats lose position markers in rivers

### ISSUE THREAD

**Issue by duncanwebb** [jglrxavpok/Moar-Boats#82]
Hopefully I can explain the case clearly.

I've a golden ticket in a boat with a path up a river to a port that unloads and loads a boat. The boats have chunk loaders and day light sensors for power. At night the power drops to zero and if the boat is in the river it will flow down stream and in the morning when the sun is up it will have power again.

The problem is if the boat has drifted past markers then it will still try to go to its next marker and get stuck on the shore.

Would it be possible to the boat to recalculate its next position when power is restored or not to drift in rivers?

Many thanks for your time.

**Comment by jglrxavpok** [comment]
That is an oversight from my part, I will fix this in an update very soon.

**Comment by jglrxavpok** [comment]
Fixed in the next update

When an engine restarts, the boat will go to the closest waypoint before trying to follow the path, resetting its internal waypoint progression at the same time.
