### ISSUE TITLE
[1.14.4]

### ISSUE THREAD

**Issue by Seikikai** [jglrxavpok/Moar-Boats#89]
Forge 28.1.117, Just Added This Mod And Now Is Crashing On Load.

Crash: https://paste.link/p2/TB-cGE8ZISFAwzgsLJsm4g.txt
Debug: https://paste.link/p2/liMYlJfBkNLa62-dag4PVA.txt

**Comment by jglrxavpok** [comment]
I have tried reproducing the issue by installing SecretRooms 6.0.5 on Forge 28.1.117 alongside Moar Boats.
The game loads fine with both mods.
Could you send the modpack you use?

**Comment by Seikikai** [comment]
Not A Modpack, Just A Bunch Of Mods.

Anyways, Found That (JAOPCA https://www.curseforge.com/minecraft/mc-mods/jaopca) Is The Mod That Is Uncompatible
