### ISSUE TITLE
Feature Request: Add a way to add additional blocks to Icebreaker

### ISSUE THREAD

**Issue by Broam** [jglrxavpok/Moar-Boats#98]
The Ice Breaker doesn't break TerraFirmaCraft Ice or Sea Ice 'correctly' (replaces it with Vanilla Water). This makes the mod less useful for those living further north (where the oceans and lakes freeze over in winter).

**Comment by Broam** [comment]
This might be a 1.12 / 1.16 thing, but MoarBoats is checking for "IceBlock" where as the TFC Ice extends "BlockIce"

I am unsure which mod is 'at fault' here, so asking for a configurability list (and a mode where the block isn't replaced, just broken), might be the best thing

**Comment by jglrxavpok** [comment]
Fixed in 1.19 port
-> Uses #minecraft:ice tag
