### ISSUE TITLE
[1.16.5]Crash with the fishing module

### ISSUE THREAD

**Issue by DLumina** [jglrxavpok/Moar-Boats#99]
https://paste.ubuntu.com/p/kj37w77QPg/

It seems that there's a conflict between mods when rendering the boat entity, but I'm not sure which mod conflicts with MoarBoats.

I was testing the fishing module at that time, and it didn't crash before the module worked for a few seconds. So I guess it might caught up a fish and the animation caused a crash.

**Comment by jglrxavpok** [comment]
Fixed in 1.19 port
